title: "{WRAP·BLOGGER}"
description: "Wrapblogger resources."
baseurl: ""
url: ""
permalink: "/:path/"
exclude:
  - .git/
  - .bundle/
  - .sass-cache/
  - vendor/
  - .editorconfig
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  blogger-snippets:
    output: true
    permalink: "/blogger-snippets/:path/"

defaults:
  - scope:
      path: ""
      type: blogger-snippets
    values:
      layout: blogger-snippets-single

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed
