title: "Wrapblogger"
description: "Wrapblogger resources."
baseurl: ""
url: ""
permalink: "/:path/"
exclude:
  - .git/
  - .bundle/
  - .sass-cache/
  - vendor/
  - .editorconfig
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed
